services:
  proxy_reverso:
    build:
      context: ./
      dockerfile: ./ngix_server.DOCKERFILE
    env_file: "./enviroments/test/react.env"  
    hostname: proxy_reverso
    restart: always 
    ports:
      - 8082:80
      - 8449:443
    volumes:
      - ngix_servicio_volumns:/etc/nginx_config/
      - react_volumns:/usr/share/nginx/html
    networks:
      - dmz
    depends_on:
      golang_servicios:
       condition: service_healthy
  base_datos:
    build :
      context: ./
      dockerfile: ./postgres.DOCKERFILE  
    env_file: "./enviroments/test/postgres.env"  
    container_name: base_datos
    hostname: base_datos
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s 

    volumes:
      - base_datos_volumns:/var/lib/postgresql/data
    networks:
      - interna
  minio-server:
    build :
      context: ./
      dockerfile: ./minio.DOCKERFILE
    env_file: "enviroments/test/minio.env"     
    restart: always
    hostname: minio_server
    #healthcheck:
    #  test: ["CMD-SHELL", "curl -I http://localhost:9000 "]
    #  interval: 10s
    #  retries: 5
    #  start_period: 1s
    #  timeout: 50s  
    volumes:
      - minio_volumns:/usr/bin/minio/data      
    ports:
      - 9001:9001
    networks:
      - interna

  pdf_servicio:
    build :
      context: ./
      dockerfile: ./Java_service.DOCKERFILE
    restart: always
    hostname: pdf_servicio     
    networks:
      - interna
    volumes:
      - java_volumns:/app/pdf_server_spring
  golang_servicios:
    build: 
      context: ./
      dockerfile: ./Golang_service.DOCKERFILE
      args:
        Private_key: ${Private_key}
    restart: always
    hostname: golang_servicios      

    env_file: "enviroments/test/golang.env"  
    healthcheck:
      test: ["CMD-SHELL", "curl -I http://localhost:9091/ping "]
      interval: 10s
      retries: 5
      start_period: 1s
      timeout: 50s 
    depends_on:
      base_datos:
          condition: service_healthy
          restart: true
      minio-server:
          condition: service_started
      pdf_servicio:
          condition: service_started
    networks:
      - dmz
      - interna
networks:
  dmz:
    driver: bridge
  interna:
    internal: true
volumes:
  ngix_servicio_volumns:

#    driver_opts:
#       device: ./volumns/ngix
  base_datos_volumns:
#    driver_opts:
#      device: ":0./volumns/postgres"
  react_volumns:
#    driver_opts:
#      device: ":./volumns/react"
  java_volumns:
#    driver_opts:
#      device: ":./volumns/java"
  minio_volumns:
#    driver_opts:
#      device: ":./volumns/minio"
